const Trackable = require('../../BuildBus/Trackable');
/**
 * A module that can be changed by a third party.
 *
 * When Webpack loads a module into its bundles, it processes the source code
 * through a set of rules generated by Buildpack. A PublicModule is a reference
 * to that source file, meant to be passed to interceptors. Inside
 * interceptors, extensions and projects can configure the PublicModule to
 * transform in many ways.
 */
class TargetableModule extends Trackable {
    constructor(file, trackingOwner) {
        super();
        this.file = file;
        this._queuedTransforms = [];
        this.attach(this.file, trackingOwner);
    }
    addTransform(type, transformModule, options) {
        const request = this._createTransform(type, transformModule, options);
        this._queuedTransforms.push(request);
        this.track('addTransform', request);
        return this;
    }
    flush() {
        return this._queuedTransforms.splice(0, this._queuedTransforms.length);
    }
    prependSource(insert) {
        this.addTransform(
            'source',
            '@magento/pwa-buildpack/lib/WebpackTools/loaders/splice-source-loader',
            {
                at: 0,
                insert
            }
        );
    }
    _createTransform(type, transformModule, options) {
        return {
            type,
            fileToTransform: this.file,
            transformModule,
            options
        };
    }
}

module.exports = TargetableModule;
